drop table if exists DimCustomer;
create table DimCustomer(
	CustomerSK int identity(1,1) primary key,
	AlternateCustomerID int,
	Title	nvarchar(10),
	FirstName	nvarchar(50),
	LastName	nvarchar(50),
	Gender	nvarchar(3),
	Email nvarchar(50),
	PhoneNumber	nvarchar(20),
	AgeRange nvarchar(50),
	MaritalStatus nvarchar(20),
	Rented bit,
	FamilySize nvarchar(10),
	NoOfChildren nvarchar(10),
	IncomeBracket int,
	City	nvarchar(50),
	Country nvarchar(50),
	CountryCode nvarchar(20),
	Latitude float,
	Longitude float,
	StreetAddress nvarchar(150),
	StreetName nvarchar(50),
	StreetNumber int,
	StreetSuffix nvarchar(20),
	StartDate	datetime,
	EndDate		datetime,
	InsertDate datetime, 
	ModifiedDate datetime
)